name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-app:latest .
        docker tag my-app:latest my-docker-username/my-app:latest
      env:
        DOCKER_USERNAME: ${{ secrets.ajuu }}
        DOCKER_PASSWORD: ${{ secrets.dckr_pat_C575XUjJsqZNnsOrqoj67VpqEPE }}

    - name: Log in to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Push Docker image to Docker Hub
      run: docker push my-docker-username/my-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Stop and remove existing container (if any)
      run: |
        docker stop my-app-container || true
        docker rm my-app-container || true

    - name: Run the new Docker container
      run: |
        docker run -d -p 8080:80 --name my-app-container my-docker-username/my-app:latest
